apiVersion: v1
kind: PersistentVolume
metadata:
  name: demvol03-iodb
  labels:
    name: demvol03-iodb
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
    volumeID: demvol03-iodb
    