apiVersion: v1
kind: PersistentVolume
metadata:
  name: demvol01-ext4
  labels:
    name: demvol01-ext4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  portworxVolume:
    volumeID: demvol01-ext4